---
# - name: Update apt-get repo and cache
#   apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
#   become: yes

- name: check the version of CloudSight
  command: "cat /opt/iopsys/resources/server.buildproperties"
  register: ls_output

- debug: msg="{{ ls_output.stdout.split('\n') }}"

